name: Build Anify

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # This lets you trigger it manually from the Actions tab

env:
  API_KEY: temp

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: oven-sh/setup-bun@v1

    - name: Install dependencies
      run: bun install

    - name: Commit bun.lockb
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add bun.lockb || echo "No changes to commit"
        git commit -m "chore: add generated bun.lockb" || echo "No changes to commit"
        git push || echo "No changes to commit"

    - name: Run lint
      run: bun run lint

    - name: Run build
      run: bun run build
